### ISSUE TITLE
Wait for release announcement before creating PRs

### ISSUE THREAD

**Issue by fthomas** [scala-steward-org/scala-steward#1104]
This idea originated in: https://twitter.com/NicolasRinaudo/status/1198162957164777473

Scala Steward currently detects new releases by searching for newer JARs. So once a maintainer publishes newer JARs, Scala Steward starts creating PRs. For some projects publishing JARs does not mean that a new release is complete. Maintainers might still want to write release notes, create other packages, update their websites, etc. before making a release public. For these projects it would be nice if Scala Steward would wait with creating PRs until the new version is announced.

Unfortunately announcing a new release is not a standardized process and everyone does it differently - if at all. So detecting that a new version has been announced seems to the hardest part to support this feature.

Some ideas from the Twitter thread:
* Include metadata file in repos / JARs / POMs that tell Scala Steward how to detect if a new version is announced. (https://twitter.com/olafurpg/status/1198543160483491846, https://twitter.com/d6/status/1198623194036494336)
* Check that a release exists in the GitHub repo. (https://twitter.com/dwijnand/status/1198298739791806470, https://twitter.com/dwijnand/status/1198653955636703233)

In my ideal world, this would not only work with GitHub and could be used by other tools than Scala Steward.

**Comment by dwijnand** [comment]
Perhaps there should be a grace period (24 hours? 72 hours?) after which ScalaSteward sends the PRs anyway?

**Comment by SethTisue** [comment]
This came up again with the release of Scala 3.1. Library authors are merging the 3.1 bump, even though perhaps they shouldn't, because:

* https://twitter.com/SethTisue/status/1450260785762947076
* https://twitter.com/Kordyjan/status/1450406709579718660

and there isn't really official guidance on this yet, wording is still being discussed on https://github.com/scala/scala-lang/pull/1284

In the case of Scala, the release announcement _on GitHub_ does exist: https://github.com/lampepfl/dotty/releases/tag/3.1.0 , but it's just bullets, it's not the true, full release announcement, which is the blog post.

So... I don't know, this is hard. Maybe if there are only JARs on Maven Central but no GitHub release, wait 72 hours, and if there is a GitHub release, wait 24 hours?

I'm rambling a bit, but, another thought: it's actually valuable for the steward to send version-bump PRs out ASAP, because then CI runs and we get early notice of problems. But that doesn't mean we actually necessarily want the PRs _merged_ immediately. But I'm not sure how the Steward could or should handle that. Maybe it's up to the library authors to consider being cautious and not just immediately merging. 🤷

**Comment by fthomas** [comment]
I think we should wait a bit until the community has figured out how to deal with Scala 3 updates. If the consensus will be that everyone publishes with 3.0.latest and tests with 3.0.latest and 3.latest.latest (which is Scenario C in https://github.com/typelevel/cats/pull/4016#issuecomment-946989358) Scala Steward will handle this situation just fine: it will keep 3.latest.latest up-to-date and only bumps the minor versions of 3.0.latest.

**Comment by fthomas** [comment]
This came up again with the release of Scala 2.13.7 and a thread on contributors.scala-lang.org: https://contributors.scala-lang.org/t/coordinate-compiler-and-tooling-releases/5312

**Comment by alejandrohdezma** [comment]
Given that all the changes in tooling for new releases of Scala are a matter of having a compatible version of the `semanticdb`... couldn't we just add a check when updating Scala versions that a compatible `https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_$scalaVersion` exists?. Maybe under a boolean CLI argument so people can decide if they want to activate the check or not.

**Comment by fthomas** [comment]
@alejandrohdezma This might improve the situation for Scala releases but I'd like to give every library maintainer the possibility to delay Scala Steward PRs until the release announcement has been published.

**Comment by alejandrohdezma** [comment]
Maybe with a custom SBT plugin that adds a new POM property under `project.properties`, like SBT does for SBT plugins. We could have something like:

```xml
<properties>
    <releaseSource>github-release</releaseSource>
</properties>
```

And then Scala Steward will check for the presence of this value and use the value from `scm.url` to check if there's a release for that version.

What do you think?

**Comment by fthomas** [comment]
I like it but @SethTisue brought up some arguments against modifying the POM in https://contributors.scala-lang.org/t/coordinate-compiler-and-tooling-releases/5312/37. To move forward here I suggest designing this feature such that retrieving the release notes URL is just an implementation detail. We could start with a new configuration in Scala Steward that provides these URLs and maybe switch to retrieving them from the POM later.

**Comment by fthomas** [comment]
I outlined another idea to solve this in https://contributors.scala-lang.org/t/coordinate-compiler-and-tooling-releases/5312/45. The gist of it is that we allow library maintainers to ignore specific versions globally for all Scala Steward instances. This solution would mean an extra manual step for the library maintainer but it would be small change in Scala Steward.

**Comment by fthomas** [comment]
#2337 is a draft PR for supporting a global repo config.
