### ISSUE TITLE
Steward updates different artifacts with same version number

### ISSUE THREAD

**Issue by ignasi35** [scala-steward-org/scala-steward#1314]
See https://github.com/playframework/play-ws/pull/461/files#diff-0:

![Screenshot 2020-02-11 at 12 05 46](https://user-images.githubusercontent.com/762126/74231435-db9daa00-4cc6-11ea-886b-4392a56f7412.png)

The steward was updating `scalafmt` from `2.0.1` to `2.0.7` and (incidentally) `sbt-pgp` got updated from `2.0.1` to `2.0.7` (which doesn't exist) too.

**Comment by mzuehlke** [comment]
I'm pretty sure this is the same as:
* #1184
* #129 
* #127

**Comment by usommerl** [comment]
It looks like I have another instance of this issue here: https://github.com/usommerl/graalnative4s/pull/65/files

![Update-odin-core-odin-slf4j-to-0-11-0-by-scala-steward-·-Pull-Request-65-·-usommerl-graalnative4s](https://user-images.githubusercontent.com/4050763/107691058-42bfb700-6cab-11eb-9fcb-5037b7c72892.png)

**Comment by fthomas** [comment]
Thanks for the report, @usommerl. That looks similar to the issue that was fixed with https://github.com/scala-steward-org/scala-steward/pull/1945. I think the problem was that Scala Steward found "odin" in "c**o**m.ee**d**3s**i**9**n** % sbt-buildinfo". We could make sure that is indeed fixed by that issue by adding another test case.

**Comment by usommerl** [comment]
@fthomas I'm glad you could use it as a test case. Thanks for your work on scala-steward! I can't count how many hours it has saved me already. :clap:

**Comment by fthomas** [comment]
Thanks @usommerl, that's great to hear!
