### ISSUE TITLE
Error on sbt installed by coursier/cs

### ISSUE THREAD

**Issue by yaroot** [scala-steward-org/scala-steward#1698]
I switched to `cs install sbt` for some time and didn't notice this.

The error is very obscure (unrelated message), but after deleting workspace this error shows up

```
[error] Expected symbol
[error] Not a valid command: -
[error] Expected end of input.
[error] Expected '--'
[error] Expected 'debug'
[error] Expected 'info'
[error] Expected 'warn'
[error] Expected 'error'
[error] Expected 'addPluginSbtFile'
[error] -batch
[error]  ^
```

**Comment by fthomas** [comment]
It seems that sbt installed by coursier does not support the [`-batch` and `-no-colors` options](https://github.com/scala-steward-org/scala-steward/blob/1abad4bea5c3f3d9a3dece02e6531a0b61e0359c/modules/core/src/main/scala/org/scalasteward/core/buildtool/sbt/SbtAlg.scala#L111). Can you find a way to disable the supershell and colors that works with sbt's own shell script and coursier's launcher?

**Comment by yaroot** [comment]
I switch back to stock sbt for now

**Comment by fthomas** [comment]
Using `JAVA_OPTS` works for me for sbt's own script and coursier's launcher:
```sh
JAVA_OPTS="-Dsbt.color=false -Dsbt.supershell=false $JAVA_OPTS" sbt compile
```
Relevant documentation:
 * https://www.scala-sbt.org/1.x/docs/Command-Line-Reference.html#Command+Line+Options
 * https://get-coursier.io/docs/cli-install.html#java-options

**Comment by fthomas** [comment]
Btw, the `-no-colors` option is there since the first commit of this repo (https://github.com/scala-steward-org/scala-steward/commit/dc938740f9036bc053d69756837cc1ff46daf59b#diff-61a5e78c575411a38676310ef7cc129c86fd859018daa28f2447b39ec2ec6a1eR9) and `-batch` was added in https://github.com/scala-steward-org/scala-steward/commit/de3360fe9be26a41ab996c6bc94ae40a40f4b8f7.
