### ISSUE TITLE
Update dependencies in bulk / batch

### ISSUE THREAD

**Issue by joroKr21** [scala-steward-org/scala-steward#1748]
This would reduce the maintenance burden on approving / merging update PRs and also save some CI compute.
It's especially annoying for repositories that have enabled the setting that requires PR branches to be up to date.

Ideas:
 * Could be configurable in `.scala-steward.conf`
 * Could only apply for patch and minor versions

**Comment by fthomas** [comment]
This sounds similar to #413. If it is the same, I don't like it for the reasons given in https://github.com/scala-steward-org/scala-steward/issues/413#issuecomment-585410159.

**Comment by joroKr21** [comment]
Argh, how come the words "batch" or "bulk" never appeared in that issue? 😂 

> The set of updates that are included in such a PR depend on the time it was created. A second later there might be another dependency with an update which would have been included in the PR. On the next Scala Steward run, should this dependency be included in this PR or should a new one be created? Would the new one include the updates of the previous PR?

There would be only PR for patch and minor version updates, major version updates as before.
New updates would be added to the existing PR if there is one.

> We loose the ability to detect if there is already a PR for a particular update. Currently it is possible to delete the complete persistent state Scala Steward created and run it again and it would find the PRs it created before again and would not create duplicated PRs for the same update. We can do this because each update corresponds to a distinct branch name which we can search for. I don't see how this could be done when updates are bundled in one PR.

We don't lose this ability because we only need one fixed branch name.

> A lot of new code that needs to be maintained. The current code assume that one update corresponds to one branch and one PR. A bundle PR would break that assumption and there needs to be code that accounts for that. I don't think that the benefits of this feature outweigh the maintenance costs.

That is a fair point. If the architecture of `scala-steward` would have to change substantially to support this use case then contributing a solution would be challenging.

**Comment by tarmath** [comment]
Howdy!

Bundling all updates within a single one makes a lot of sense for us. We currently only enable our internal libraries/packages to be updated rather than all external dependencies, and as things stand, we are getting a ton of PRs in a great many microservices, which not only clash with one another, but also over time completely overtakes our git commit history. 

If batching expects only one PR to be around, and does nothing as long as that PR is still open, wouldn't that take care of all corner cases/issues brought up, while keeping things extremely simple to manage code wise?

I don't mean to hijack this issue with a different proposal entirely, so if this doesn't fit the original request I can certainly create another one. Perhaps this encompasses more than just batching, but is more of a "simple one pr mode" or something like that? And of course, if you don't like that neither it's fine. 

At any rate, I wanted to thank you for this great plugin!

**Comment by fthomas** [comment]
> At any rate, I wanted to thank you for this great plugin!

Thanks!

And thank you all for your input. I understand your the reasons why you want this feature in Scala Steward but I'm still not convinced that the benefits outweigh the costs. I'd encourage anyone who wants this feature to develop, maintain, and use it in a fork of Scala Steward. If you can demonstrate that the maintenance costs over a longer period are not as high as I expect them to be, I might reconsider integrating this feature in Scala Steward. I'm closing this issue for now.

**Comment by joroKr21** [comment]
An alternative I've been considering is to develop a GitHub action that batches green update PRs together after the fact. But I didn't have time yet to try and implement something like that.

**Comment by fthomas** [comment]
@alejandrohdezma posted a recipe for something like that in https://github.com/scala-steward-org/scala-steward-action/issues/304#issuecomment-956436757.
