### ISSUE TITLE
[on-prem] Update is skipped completely if there was previous issue

### ISSUE THREAD

**Issue by eugeniyk** [scala-steward-org/scala-steward#1912]
Hi there
We're running scala-steward on prem (github) and noticed that once it stopped sending updates per particular repos:

```
2021-02-01 10:11:22,810 INFO  ──────────── Steward {org}/{proj-name} ────────────
2021-02-01 10:11:22,818 INFO  Check cache of {org}/{proj-name}
2021-02-01 10:11:22,842 DEBUG Write /opt/ag-scala-steward-workplace/workspace/store/refresh_error/v1/github/{org}/{proj-name}/refresh_error.json
2021-02-01 10:11:22,846 ERROR Steward {org}/{proj-name} failed
org.scalasteward.core.repocache.RepoCacheAlg$$anon$1: Skipping due to previous error
```

checking error log in `/opt/ag-scala-steward-workplace/workspace/store/refresh_error/v1/github/{org}/{proj-name}/refresh_error.json`:
```
{
  "failedAt" : 1611962373257,
  "message" : "'SBT_OPTS=-Xmx4096m -Xss8m -XX:MaxMetaspaceSize=1024m sbt -Dsbt.color=false -Dsbt.log.noformat=true -Dsbt.supershell=false ;+ stewardDependencies;reload plugins;stewardDependencies' exited with code 1\n[info] welcome to sbt 1.3.13 (Oracle Corporation Java 1.8.0_252)\n[info] loading global plugins from /home/ag-steward-svc/.sbt/1.0/plugins\n[info] loading settings for project {proj-name} from plugins.sbt ...\n[info] loading project definition from /opt/ag-scala-steward-workplace/workspace/repos/{org}/{proj-name} project\n[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.\n[info] loading settings for project root from build.sbt,version.sbt ...\n[info] loading settings for project cucumber from build.sbt ...\n[info] set current project to {proj-name} (in build file:/opt/ag-scala-steward-workplace/workspace/repos/{org}/{proj-name}/)\n[error] Expected ';'\n[error] Not a valid command: stewardDependencies\n[error] Not a valid project ID: stewardDependencies\n[error] Expected ':'\n[error] Not a valid key: stewardDependencies (similar: allDependencies, rpmDependencies, excludeDependencies)\n[error] + stewardDependencies\n[error]                      ^\n"
```

Removing `/opt/ag-scala-steward-workplace/workspace/store/refresh_error/v1/github/{org}/{proj-name}/refresh_error.json` seems solved the problem and subsequent update is successful

Is it expected behavior?

**Comment by fthomas** [comment]
Yes, this expected behaviour. See https://github.com/scala-steward-org/scala-steward/pull/997 for the reason why we are doing it. But I admit that is probably only useful if you're running Scala Steward for a lot of public repos and can't fix them all if Scala Steward fails to load their builds. If Scala Steward is used in a closed environment where it is only working on a handful of repos, the `RefreshErrorAlg` is probably more of a hindrance than a help. I would accept a PR that enables the `RefreshErrorAlg` only if a new command-line option is given.

**Comment by eugeniyk** [comment]
Thanks for reply @fthomas, will try to add settings, thanks

**Comment by javierarrieta** [comment]
Hi, we are being hit by the same problem in our on premise installation. I will be happy to contribute a configuration for this. I am wondering if the configuration would be:

- refresh period (now hardcoded to 7 days)
- disable backoff completely
- both

How do you think the configuration should be done @fthomas ? The default will be the current behaviour

**Comment by fthomas** [comment]
Making the period configurable would be nice but is a bit more effort to implement than a simple boolean flag. Either of them is fine with me. I wouldn't add both options because setting the period to zero would be the same as disabling it completely.
I also would set the default to "disabled" because I think this waiting period only makes sense for my public Scala Steward instance. It is less work if I change this for my installation compared to everyone else disabling it for their private installations.

**Comment by javierarrieta** [comment]
Hey, that sounds reasonable, I will add just a period then as `FiniteDuration`, but I think keeping the default to the current configuration will create less problems as it is currently a _feature_ and the change in behaviour might puzzle people.
