### ISSUE TITLE
Grouping doesn't respect artifact migration

### ISSUE THREAD

**Issue by mzuehlke** [scala-steward-org/scala-steward#2376]
While investigating how to fix #1976 I found that the functions `groupByArtifactIdName`  and  `groupByGroupId` don't respect the fields `newerGroupId` and `newerArtifactId` when grouping:

https://github.com/scala-steward-org/scala-steward/blob/b39fdc750c32a56dcf1a5b5bbffd413771d1e90e/modules/core/src/main/scala/org/scalasteward/core/data/Update.scala#L134-L142

https://github.com/scala-steward-org/scala-steward/blob/b39fdc750c32a56dcf1a5b5bbffd413771d1e90e/modules/core/src/main/scala/org/scalasteward/core/data/Update.scala#L144-L152

https://github.com/scala-steward-org/scala-steward/blob/b39fdc750c32a56dcf1a5b5bbffd413771d1e90e/modules/core/src/main/scala/org/scalasteward/core/data/Update.scala#L65-L70

I'm not totally sure, but I guess this is not correct.

**Comment by fthomas** [comment]
You're right. I think the underlying problem is that we don't retain the newer groupId and artifactIds when `Single` updates are grouped into `Group` updates since `Group` has no fields for those. Maybe the easiest solution here would be to change `Group` to `case class Group(singles: Nel[Single])` with the implicit contract that all single updates in `Group` have the same groupId, version, newer versions, and newer groupId.

**Comment by fthomas** [comment]
I would say this is also related to #1974.

**Comment by mzuehlke** [comment]
Duplicate of #1974
