### ISSUE TITLE
SBT project files being turned into Scala 3

### ISSUE THREAD

**Issue by ScoreUnder** [scala-steward-org/scala-steward#2422]
Example: https://github.com/ScoreUnder/canti-bot/pull/88/files

Result: https://gurren.score.moe/jenkins/blue/organizations/jenkins/canti-bot/detail/master/192/pipeline

scala-steward seems to be trying to migrate SBT project files to scala 3, but SBT doesn't appear to support this, so it is throwing an error. Is this a misconfiguration on my part? I am using scalafmt, but `sbt scalafmtAll` doesn't seem to format as many files as scala-steward does.

**Comment by fthomas** [comment]
Scala Steward uses the [`scalafmt` CLI](https://scalameta.org/scalafmt/docs/installation.html#cli) (instead of `sbt-scalafmt` because it is faster) to reformat changed files. If you run the CLI yourself, you'd see the Scala 3 changes yourself. I think the best option here is to tweak your `.scalafmt.conf` so that `runner.dialect = scala3` applies not to sbt build files. The Scalafmt docs have an example how to limit the `runner.dialect` to a subset of files: https://scalameta.org/scalafmt/docs/configuration.html#scala-dialects

**Comment by ScoreUnder** [comment]
A bare invocation of scalafmt does indeed seem to overwrite those files with scala 3 equivalents. After configuring it properly, it no longer happens. Notably though, it didn't happen last time the update commit was made (before `.scalafmt.conf` changes), so I'm not sure if there's a way to test it very scientifically. With the bare invocation of scalafmt working properly now though, I guess I'll assume it's working and reopen if not. Thanks for the help!

**Comment by fthomas** [comment]
> Notably though, it didn't happen [last time the update commit was made](https://github.com/ScoreUnder/canti-bot/pull/91/files)

This is probably due to https://github.com/scala-steward-org/scala-steward/pull/2380. The `scalafmt.runAfterUpgrading` now also controls if `scalafmt` is run after an ordinary version bump.
