### ISSUE TITLE
[ON HOLD] Add a way to skip archived/readonly repositories

### ISSUE THREAD

**Issue by shnapz** [scala-steward-org/scala-steward#2963]
If github project is archived and made readonly scala-steward still clones it and attempts to create PRs.
Suggestion is to detect that repo is archived on the first step, print corresponding message and skip it.
This mode could be optional.
Positive outcome: 1) saves resources 2) makes archived repos easily identifiable in logs, so that they can be removed from the config

**Comment by fthomas** [comment]
Archived repositories should already be skipped since https://github.com/scala-steward-org/scala-steward/pull/2514. Is that not working anymore?

**Comment by shnapz** [comment]
Need to verify the latest version

**Comment by fthomas** [comment]
Closing for now.

Comment here if you find that Scala Steward still clones archived repos. We can reopen this issue then.

**Comment by rtyley** [comment]
I think I would prefer that that encountering archived repository gives a logged warning, rather than an exception (and ideally this shows up in the summary file from https://github.com/scala-steward-org/scala-steward/pull/3071).

The exception means that the whole Scala Steward steward run will be [reported as a failure when running in a GitHub Action](https://github.com/guardian/scala-steward-public-repos/actions/runs/6970645883/job/18969003724#step:5:864), which is unduly severe and loses the updates to the PR datastore.

**Comment by fthomas** [comment]
I don't mind if this is just a warning.
