### ISSUE TITLE
Sbt updates not being included in PRs

### ISSUE THREAD

**Issue by bpholt** [scala-steward-org/scala-steward#3051]
I've noticed since we enabled PR grouping that we get pull requests from our Scala Steward instance that claim to update sbt, but the commits that would make those changes are not included in the PR. This shows up in the logs:

```
2023-05-12 15:43:16,280 WARN Unable to bump version for update org.scala-sbt:sbt : 1.8.2 -> 1.8.3
2023-05-12 15:43:16,439 WARN Unable to bump version for update org.scala-sbt:(scripted-plugin, scripted-plugin_2.12) : 1.8.2 -> 1.8.3
```

Here's the resulting PR description:

> Updates:
> 
> * [org.scala-sbt:sbt](https://github.com/sbt/sbt) from 1.8.2 to 1.8.3
>   + [GitHub Release Notes](https://github.com/sbt/sbt/releases/tag/v1.8.3) - [Version Diff](https://github.com/sbt/sbt/compare/v1.8.2...v1.8.3)
> * [org.scala-sbt:scripted-plugin](https://github.com/sbt/sbt) from 1.8.2 to 1.8.3
>   + [GitHub Release Notes](https://github.com/sbt/sbt/releases/tag/v1.8.3) - [Version Diff](https://github.com/sbt/sbt/compare/v1.8.2...v1.8.3)
> * [org.typelevel:cats-effect](https://github.com/typelevel/cats-effect) from 3.4.11 to 3.5.0
>   + [GitHub Release Notes](https://github.com/typelevel/cats-effect/releases/tag/v3.5.0) - [Version Diff](https://github.com/typelevel/cats-effect/compare/v3.4.11...v3.5.0)
> 
> 
> I'll automatically update this PR to resolve conflicts as long as you don't change it yourself.
> 
> If you have any feedback, just mention me in the comments below.
> 
> Configure Scala Steward for your repository with a [`.scala-steward.conf`](https://github.com/scala-steward-org/scala-steward/blob/f12a86103f9f59b59628405e2b8648d9643706bc/docs/repo-specific-configuration.md) file.
> 
> Have a fantastic day writing Scala!
> 
> <details>
> <summary>Files still referring to the old version numbers</summary>
> 
> The following files still refer to the old version numbers.
> You might want to review and update them manually.
> ```
> project/build.properties
> src/main/g8/project/build.properties
> ```
> </details>
> <details>
> <summary>Adjust future updates</summary>
> 
> Add these to your `.scala-steward.conf` file to ignore future updates of these dependencies:
> ```
> updates.ignore = [
>   { groupId = "org.scala-sbt", artifactId = "sbt" },
>   { groupId = "org.scala-sbt", artifactId = "scripted-plugin" },
>   { groupId = "org.typelevel", artifactId = "cats-effect" }
> ]
> ```
> Or, add these to slow down future updates of these dependencies:
> ```
> dependencyOverrides = [
>   {
>     pullRequests = { frequency = "30 days" },
>     dependency = { groupId = "org.scala-sbt", artifactId = "sbt" }
>   },
>   {
>     pullRequests = { frequency = "30 days" },
>     dependency = { groupId = "org.scala-sbt", artifactId = "scripted-plugin" }
>   },
>   {
>     pullRequests = { frequency = "30 days" },
>     dependency = { groupId = "org.typelevel", artifactId = "cats-effect" }
>   }
> ]
> ```
> </details>
> 
> labels: library-update, early-semver-patch, semver-spec-patch, version-scheme:early-semver, early-semver-minor, semver-spec-minor, old-version-remains, commit-count:1

I would have expected the `build.properties` files in the repo to be updated with the new sbt version.

FWIW, this also happens in repos that are not G8 templates and don't mention `scripted-plugin`, too.

**Comment by alejandrohdezma** [comment]
Hey @bpholt, do you have (or can create a public barebone replica) of the repository where you are having these issues?

**Comment by d-g-n** [comment]
Hi, i'm also seeing this issue with a private repository, 
```
2023-05-15 08:56:55,212 WARN  Unable to bump version for update org.json4s:(json4s-jackson, json4s-jackson_2.13) : 4.0.5 -> 4.0.6
2023-05-15 08:56:55,374 WARN  Unable to bump version for update org.scala-sbt:sbt : 1.8.2 -> 1.8.3
2023-05-15 08:56:55,556 WARN  Unable to bump version for update org.scala-sbt:sbt-dependency-tree : 1.8.2 -> 1.8.3
2023-05-15 08:56:56,679 WARN  Unable to bump version for update org.specs2:(specs2-mock, specs2-mock_2.13) : 4.19.2 -> 4.20.0
```

The repo is a standard scala repo format, have included truncated images showing the relevant parts of the files
![image](https://github.com/scala-steward-org/scala-steward/assets/10690618/2c623c7c-f722-4336-b395-e5d5df1634e7)
![image](https://github.com/scala-steward-org/scala-steward/assets/10690618/b16a020c-24cf-4917-a286-2ea2de31dd95)

No other files have been updated in the PR. Although looking at this again, sbt-dependency-tree is added via `addDependencyTreePlugin` so that's likely why that one can't update, and even though it states that json4s-jackson and specs2-mock cannot be updated, they have both actually been updated, it's just the sbt version that hasn't

The project/build.properties file looks like this

![image](https://github.com/scala-steward-org/scala-steward/assets/10690618/b661a294-7e31-4696-85a4-fb11a9fb04af)

**Comment by alejandrohdezma** [comment]
That is weird, I'm also using the `grouping` feature for my own repositories and [just receive the SBT update along with the other ones](https://github.com/alejandrohdezma/sbt-github/pull/493). Can any of you share the `.scala-steward.conf` file you're using?

**Comment by d-g-n** [comment]
Sure, this is my conf file:
```

updates.fileExtensions = [".scala", ".sbt", ".sbt.shared", ".sc", ".yml", ".md", ".markdown", ".txt"]

updatePullRequests = "always"

pullRequests.grouping = [
  { name = "all", "title" = "Dependency updates", "filter" = [{"group" = "*"}] }
]
```

**Comment by d-g-n** [comment]
Oh and i forgot to include it earlier, i'm running `v0.23.0-62-8b8cd4b9-SNAPSHOT` which appears to be the latest commit on main

**Comment by d-g-n** [comment]
Looks like that's fixed it, thank you:
![image](https://github.com/scala-steward-org/scala-steward/assets/10690618/06f3abfc-0211-4a4c-9121-667d34848a0b)

**Comment by d-g-n** [comment]
Only other thing i've noticed related to the grouping logic, it seems to create commits again for any updated leading to a tremendous amount of new commits, is this intentional? (I know the repeated commits pictured are not the same, but they are duplicated above not directly in the picture), thanks again for your help
![image](https://github.com/scala-steward-org/scala-steward/assets/10690618/d18a4e5b-f4d2-4a4b-83b7-5aab5e96cbbe)

**Comment by alejandrohdezma** [comment]
Yes, if the PR is kept unmerged and a second run occurs, the commits will be reverted and applied again
