### ISSUE TITLE
Error compiling the sbt component 'compiler-bridge_2.12' using 0.31.0 with an SBT 1.8.0 project

### ISSUE THREAD

**Issue by alexklibisz** [scala-steward-org/scala-steward#3467]
Hi all, today I tried to upgrade from 0.30.2 to 0.31.0 and tested it on an SBT 1.8.0 project. 

0.30.2 runs fine, but 0.31.0 fails with a long cryptic error that seems to ultimately boil down to:

```
2024-11-05T20:27:12.2882030Z [info] Attempting to fetch org.scala-sbt:compiler-bridge_2.12:1.8.0.
2024-11-05T20:27:12.2882579Z [error] (Compile / compileIncremental) Error compiling the sbt component 'compiler-bridge_2.12'
2024-11-05T20:27:12.2883039Z [warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
```

I ran them minutes apart with no changes to the repo, and retried the failure a couple times, so the scala-steward version seems to be making the difference here.

If it's not obvious what's happening from that log, I can cleanup/redact and attach the full error logs. Just LMK.

**Comment by mzuehlke** [comment]
Sadly the list of changes for that release is pretty long 😢 
If you could provide more detailed logs that may already be helpful 🤞

**Comment by alexklibisz** [comment]
Sure thing. Here is the log starting when we invoke scala-steward via Docker and ending at the error. [scala-steward-0.31.0-error.log](https://github.com/user-attachments/files/17638750/scala-steward-0.31.0-error.log)

I redacted several identifiers, but it should hopefully still reflect what's going on.

**Comment by mzuehlke** [comment]
Thanks,
from the logs I see that the problem is caused by running sbt 1.8.0 with JDK 21 (which isn't supported).

This PR https://github.com/scala-steward-org/scala-steward/pull/3417 bumped the base image of the Scala Steward base image from JDK 11 to JDK 21. The PR didn't fully solve the issue it tried to solve https://github.com/scala-steward-org/scala-steward/issues/2590
This will probably result in error in the public instance, too (/cc @tgodzik)
I will switch back to a JDK11 base image.
